name: Continuous Integration
run-name: Continuous Integration
on:
  push:
    branches:
      - matrix
  pull_request:
    branches:
      - matrix
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Security
        run: echo "Security Mock"
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency
        run: echo "Dependency Mock"
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONARCLOUD}}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=ximatriarx
            -Dsonar.projectKey=radix
            -Dsonar.sources=.
            -Dsonar.verbose=true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONARCLOUD}}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=ximatriarx
            -Dsonar.projectKey=radix
            -Dsonar.sources=.
            -Dsonar.javascript.coverage.reportPaths=""
            -Dsonar.tests=""
            -Dsonar.verbose=true
