name: Release
run-name: Release
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build Mock"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy Mock"
